//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int Id { get; set; }
        public string employee_name { get; set; }
        public string employee_email { get; set; }
        public string employee_address { get; set; }
        public string employee_phoneNo { get; set; }
    }
}
